# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Organizacion',
                'db_table': 'blizuu_orgs',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='QueryStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateTimeField(auto_now_add=True)),
                ('query_text', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Consulta API',
                'db_table': 'blizuu_queries',
                'verbose_name_plural': 'Consultas API',
            },
        ),
    ]
