# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='login',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
